### ISSUE TITLE
Cannot add GET requests to BatchRequest - "unexpected end of JSON input"

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-go-core#142]
Adding a GET request to a `BatchRequest` results in an error:

```
error(*encoding/json.SyntaxError) *{msg: "unexpected end of JSON input", Offset: 0}
```

## Repro

```go
// Use the request builder to generate a regular
// request to /me
meRequest, err := client.Me().
    CreateGetRequestInformation(context.Background(), nil)
if err != nil {
    return err
}

// Set the baseurl to workaround
// https://github.com/microsoft/kiota/issues/2061
meRequest.PathParameters["baseurl"] = client.GetAdapter().GetBaseUrl()

// Create batch and add meRequest
batch := msgraphcore.NewBatchRequest()
meRequestItem, err := batch.AddBatchRequestStep(*meRequest)
if err != nil {
    return err
}
```

## More information

This seems to be a bug here:

https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/efb4b6bb6da1a34505ef78d18ea36cb57e29fd23/batch_requests.go#L119-L123

For GET requests, `Content` is always empty. Calling `json.Unmarshal` on an empty array generates that error.

![image](https://user-images.githubusercontent.com/8966342/207427998-2dc8780a-8b6d-405d-bfc6-640f234d5ef0.png)

**Comment by jasonjoh** [comment]
Assigned to @rkodev per @baywet

**Comment by jasonjoh** [comment]
For anyone hitting this, you can workaround it with this:

```go
emptyJson := []byte("{}")
meRequest.Content = append(meRequest.Content, emptyJson...)
```

**Comment by rkodev** [comment]
Thanks for reporting this @jasonjoh , For the next release the missing raw url will be conditionally added to the path parameters

This snippet , `meRequest.PathParameters["baseurl"] = client.GetAdapter().GetBaseUrl()` , will not be required
