### ISSUE TITLE
Can PageIterator expose odata links from pages?

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go-core#190]
We need to iterate over paginated delta results. We also want to save the `@odata.deltaLink` for the final page so that we can track recent changes. Unfortunately, the `PageIterator` doesn't expose the page delta links. Is there any way to expose the odata info for pages? Perhaps introduce a new function?

```
func (pI *PageIterator[T]) IterateWithOdata(context context.Context, callback func(pageItem T, pageOdataInfo OdataLinks) bool) error
```

Another option would be to iterate pages rather than just items, where `page` is a `*CollectionResponse`

```
func (pI *PageIterator[T]) IterateResponses(context context.Context, callback func(pageCollectionResponse Parsable) bool) error
```

I would be open to PRing a change.

**Comment by baywet** [comment]
Thanks for reporting this @eric-millin 
What would you think of the Iterate method returning (*string, error) instead of (error)?

https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/c634ec0a433d3d0ff2a12ad7307c7e6fe3c6e2e4/page_iterator.go#L81

@andrueastman how do you return the delta link in page iterator in dotnet?
@maisarissi we'd probably need to address it before GA. I don't think it's a big change however.

**Comment by eric-millin** [comment]
Here's a simple, non-disruptive solution that introduces a new function. https://github.com/eric-millin/msgraph-sdk-go-core/commit/f9476f44c92cc0d0f3519f1d37218e7cf8571a82

```go
func (pI *PageIterator[T]) IterateResults(context context.Context, callback func(pageResponse interface{}) bool) error
```

You'd use it like
```go
	pageIterator, err := NewPageIterator(resp, reqAdapter, parsableFactory)
	callbackFunc := func (resp interface{}) bool {
            cr := resp.(*SomeAmazingDeltaCollectionResult)
            delta := cr.GetOdataDeltaLink()
	    // do stuff
	    return true
	}
	err := pageIterator.IterateResults(context.Background(), callbackFunc)
```

**Comment by andrueastman** [comment]
> @andrueastman how do you return the delta link in page iterator in dotnet?

At the moment, this is a property in the pageIterator instance. 
Calling the code below will page to the last nextLink and iteration will stop as no more pages are available.

```cs
await pageIterator.IterateAsync();
```
If a deltaLink is present, it can be accessed as `pageIterator.Deltalink` ref [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/13968a628058ac68e4a7b843f50786e37e299ce0/src/Microsoft.Graph.Core/Tasks/PageIterator.cs#LL36C23-L36C33).
