### ISSUE TITLE
time format inconsistency

### ISSUE THREAD

**Issue by crewjam** [microsoftgraph/msgraph-sdk-go-core#212]
When the API returns the following error:

```
{"error":{"code":"accessDenied","message":"Self-service operations are currently not supported for user XXX.","innerError":{"message":"Self-service operations are currently not supported for user XXX.","date":"2023-07-07T13:06:51","request-id":"YYY","client-request-id":"ZZZ"}}}
```

The SDK fails to parse the response body because the `date` field is not properly formatted according to:

```
parsed, err := time.Parse(time.RFC3339, *v)
```

Note the missing "Z" or some other time zone designation at the end of the date field.

**Comment by rkodev** [comment]
Hi @crewjam Thanks for trying this SDK. Are you able to share which endpoint is resulting to the response?

**Comment by meain** [comment]
@rkodev The error is when the sdk is trying to parse the date in an error. You can try something simple like the following with an invalid `userID` to repro the same.

```go
	client := msgraphsdk.NewGraphServiceClient(adapter)
	u, err := client.Users().
		ByUserId(userID).
		Drive().
		Get(context.Background(), nil)
```

**Comment by crewjam** [comment]
Thanks for reply, all. Yes, @meain 's example does reproduce. The exact request I was doing was:

```
graphClient.Users().ByUserId(directoryEntry.ExternalID).Authentication().PasswordMethods().Get(ctx, nil)
```
