### ISSUE TITLE
Run Raptor against Go SDK

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-go-core#24]
As part of our commitment to deliver high quality SDKs, for GA we must run [Raptor](https://github.com/microsoftgraph/msgraph-sdk-raptor) against the Go SDK.

**Comment by baywet** [comment]
clarify "run" do you mean snippets should compile or do you mean they should actually execute? Also it's probably worth creating an additional issue on the raptor repo to get that work on the team's radar and link it here.

**Comment by maisarissi** [comment]
For a first iteration, at least have the "snippets should compile" since for the second part "actually execute" requires even more work from another team. Let's not block GA awaiting execution tests.
I have already created one issue on the Raptor repo and linked here as a dependency:
![image](https://user-images.githubusercontent.com/22648831/145113537-0c9bafd9-ce03-416a-acef-b9260baaec96.png)

But unfortunately, it seems like it's only possible to see it when ZenHub is connected.

Depends on https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/705

**Comment by ddyett** [comment]
closing this instance and tracking the main one on the new board.
