### ISSUE TITLE
Http/2 validation

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-go-core#28]
AGS is rolling out HTTP/2 support. It is already available in Canary.

The goal here is to test our current client against Canary to validate that it's using http2 when available and there's no issues related to http.2 (response header casing etc.)

Details to connect to Canary are available on the dedicated Teams discussion.

**Comment by jobala** [comment]
All tested scenarios work with HTTP/2

**Comment by baywet** [comment]
thanks for the work and reverting here!
