### ISSUE TITLE
Support sovereign clouds

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/msgraph-sdk-go-core#30]

**Comment by baywet** [comment]
@jobala this is already supported today with the current service libs through the ability to set the base url on the request adapter and change the scope/audiences in Azure identity.
In the future, we might stand-up dedicated service libraries for those national clouds, and there will be the self service option. 
Can you expand on what you feel is missing pleae?

**Comment by jobala** [comment]
National Clouds is implemented in Python core, that why I thought Go core sdk will need the feature as well. Closing.
