### ISSUE TITLE
Logging Handler

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/msgraph-sdk-go-core#31]
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/LoggingHandler.md

**Comment by baywet** [comment]
Hi @mbarnes ,
Thanks for sharing this.
Providing the ability to log request and responses has always been something we've debated a lot internally.
On one hand it can be really useful to debug.
On the other, somebody could easily forget to remove it and ship it in production, logging sensible data.
A middle ground could be to enable conditional compilation so the code is only present for debug builds. But I'm not sure it's a thing in go like it is in dotnet.
Regardless we have our architect working on an observability spec (tracing, logging and metrics) for all the kiota based sdks.

**Comment by baywet** [comment]
https://github.com/microsoft/kiota/issues/1486

**Comment by mbarnes** [comment]
Yeah, conditional compilation isn't a thing in Go unfortunately.
In my case, I'm using an environment variable to enable the request/response logging.

**Comment by baywet** [comment]
A good alternative. We could also have the handler as part of the http package but not of the default handlers that are added to the client to drive enable/disable.
And when the handler is added, log very loud warnings so people notice it if enabled in production.
These are the kind of discussions we've had so far without reaching a consensus.
Cc @darrelmiller in case you want to revisit as part of your observability spec.
