### ISSUE TITLE
Block attachements of a message as an app

### ISSUE THREAD

**Issue by unglaublicherdude** [microsoftgraph/msgraph-sdk-go-core#319]
### Is your feature request related to a problem? Please describe the problem.

We are trying to implement an antivirus for teams and have already found the chatMessagePolicyViolation. When using this, a message can replaced with an alert-message and the original content is gone. But setting a policy violation will not change attachements. And when we basically replace the file on onedrive, the preview in the message will still persist which is a bit confusing for users.

### Describe the solution you'd like.

I would like a way to also remove attachements from a message when a chatMessagePolicyViolation is set.

**Comment by andrueastman** [comment]
Thanks for raising this @unglaublicherdude 

Any chance you tried updating the message by sending a PATCH request with the attachment removed? This would be a variant of example 4 at the docs link below.

https://learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&tabs=http#example-4-update-the-content-with-attachments-of-a-message-using-delegated-permissions

**Comment by unglaublicherdude** [comment]
Can this be done via a bot Account? I guess that's where we failed

**Comment by andrueastman** [comment]
The docs suggest that application permissions should work for the API. 

However, as this is really an API side functionality question, the best place to ask would be at https://aka.ms/askGraph. This repo is mainly intended for issues related to the graph SDK so we may not be best placed to answer this.
