### ISSUE TITLE
Issue creating upload session on a folder

### ISSUE THREAD

**Issue by MilitsaB** [microsoftgraph/msgraph-sdk-go-core#325]
I am trying to create an upload session to upload a file in a folder in Sharepoint. I am receiving the following error: `Cannot create an upload session on a folder`. 
I understand that an upload session cannot be created on a folder, however I am not sure how I can create one. 

This is what I am currently doing:
```
uploadSession, err := graphClient.
		Drives().ByDriveId(driveID).
		Items().ByDriveItemId(folderID).
		CreateUploadSession().
		Post(ctx, uploadSessionRequestBody, nil)
```

I noticed that the msgraph-sdk-net has a method `ItemWithPath` which is not available in the Go version (https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1353)
```
var uploadSession = await graphClient.Sites["site-id"].Drive.Items["folderId"].ItemWithPath("file.txt")
                            .CreateUploadSession(uploadProps)
                            .Request()
                            .PostAsync();
```

Any ideas on how I can do this using `msgraph-sdk-go`?

**Comment by rkodev** [comment]
Hi @MilitsaB, thanks for tryong out the SDK. Are you able to test this [example](https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=go)  i.e concatenate the folderID + itemPath + ":"

```go

uploadSession, _ := graphClient.Drives().
    ByDriveId(*myDrive.GetId()).
    Items().
    ByDriveItemId(folderID + "/"+"file.txt"+":").
    CreateUploadSession().
    Post(context.Background(), uploadSessionRequestBody, nil)

```
