### ISSUE TITLE
PageIterator repeating same page over and over

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-go-core#40]
I'm using PageIterator to iterate over messages (`/me/messages`). This continues until an error is returned from the `Iterate` function: `Fetching next page failed`

My code:

```go
query := messages.MessagesRequestBuilderGetQueryParameters{
  Select: []string{"body", "sender", "subject"},
}

options := messages.MessagesRequestBuilderGetOptions{
  H: map[string]string{
    "Prefer": "outlook.body-content-type=\"text\"",
  },
  Q: &query,
}

result, err := client.Me().Messages().Get(&options)

if err != nil {
  fmt.Printf("Error getting messages: %v\n", err)
  return
}

pageIterator, err := msgraphcore.NewPageIterator(result, adapter.GraphRequestAdapterBase,
  func() serialization.Parsable {
    return messages.NewMessagesResponse()
  })

if err != nil {
  fmt.Printf("Error creating iterator: %v\n", err)
  return
}

pageIterator.SetHeaders(map[string]string{"Content-Type": "application/json"})

iterateErr := pageIterator.Iterate(func(pageItem interface{}) bool {
  message := pageItem.(graph.Message)
  fmt.Printf("%s\n", *message.GetSubject())
  return true
})

if iterateErr != nil {
  fmt.Printf("Error iterating over messages: %v\n", iterateErr)
  return
}
```

What I've observed from debugging locally is that the `nextLink` is being generated incorrectly. On the first request (the `client.Me().Messages().Get(&options)` call), `nextLink` looks as expected:

```
https://graph.microsoft.com/v1.0/me/messages?%24select=body%2csender%2csubject&%24top=10&%24skip=10
```

But when the iterator requests the next page, it's setting `nextLink` like:

```
https://graph.microsoft.com/v1.0/me/messages?%24%24select=body%2csender%2csubject&%24%24top=10&%24%24skip=10&%24top=10&%24skip=10
```

Notice that:

- The `$` (`%24`) instances are being doubled
- The `skip` and `top` params are repeated, both with the *original* values from the very first `nextLink`, 10 and 10

On subsequent requests it just compounds (3 `$`, `skip`/`top` repeated 3 times, etc.)

**Comment by baywet** [comment]
Thanks for reporting this @jasonjoh 

This is probably because of this regex
https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/9e4c35dcdb9456332a21294dee24377d5ef561ec/graph_odata_query_handler.go#L50

```diff
-"(?i)([^$])(count|deltatoken|expand|filter|format|orderby|search|select|skip|skiptoken|top)="
+"(?i)([^$|4])(count|deltatoken|expand|filter|format|orderby|search|select|skip|skiptoken|top)="
```

Making the following change to account for encoding should account for encoding cases.

Assigning to @jobala to update the regex and add a unit test for it.

CC @andrueastman for the work he is doing in the dotnet space.
