### ISSUE TITLE
PageIterator should have an isComplete method (or similar)

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-go-core#43]
The .NET and JS iterators have a way to check if the iterator is "complete":

```csharp
while (pageIterator.State != PagingState.Complete)
```

```typescript
while (!pageIterator.isComplete())
```

Go should have something similar for consistency. This would also simplify pausing/resuming.

**Comment by jobala** [comment]
@jasonjoh the PageIterator's spec changed and JS and C# SDKs will be updated to conform to the spec and should instead have a hasNext method ie

```js
while  (iterator.hasNext) {
   // keep iterating
}
```

**Comment by jasonjoh** [comment]
That seems reasonable to me.
