### ISSUE TITLE
missing public documentation articles

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-go-core#5]
These sections of the readme point to public documentation sections that do not exist today
[getting started](https://github.com/microsoftgraph/msgraph-sdk-go-core#microsoft-graph-core-sdk-for-go)
[choosing your authentication provider](https://github.com/microsoftgraph/msgraph-sdk-go-core#22-create-an-authenticationprovider-object)

TODO:

- [ ] create the section in the public documentation (mark as preview)
- [ ] update the readme

@jasonjoh can I let you take this one on please?

**Comment by jasonjoh** [comment]
https://github.com/microsoftgraph/microsoft-graph-docs/pull/14828

**Comment by baywet** [comment]
closing since the PR has been merged.
