### ISSUE TITLE
investigate why the go doc is not available for models

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-go-core#79]
https://pkg.go.dev/github.com/microsoftgraph/msgraph-sdk-go/models shows "Documentation is too large to display." when 
https://pkg.go.dev/github.com/microsoftgraph/msgraph-sdk-go#GraphServiceClient.Admin works fine.

Originally reported in https://github.com/microsoftgraph/msgraph-sdk-go/issues/129

**Comment by deltamualpha** [comment]
Possibly related to https://github.com/golang/go/issues/51564?

**Comment by baywet** [comment]
Thanks for linking the issue.
After spending a lot of time investigating build time issues, it appears that Go was not designed for large packages. Which leads to a number of limitations. With the build time issues fixed, and the packages being flattened for the fluent API surface, the fluent API surface pkg docs is also not working properly anymore.
At least fixes have been implemented on the platform and the pages load now.
There's not much we can do about it at this point. And we have our own public docs platform to bridge the gaps with provides additional information about authorization, samples, etc...

Closing.
